### ISSUE TITLE
"Update All Bitmaps" not working anymore (Sketch 96.2)

### ISSUE THREAD

**Issue by o-l-e** [frankko/Place-Linked-Bitmap#17]
Love this plugin so much. I don't know if this i an issue because i use Google Drive locally, but bitmaps won't update anymore.

Hope there is a fix for this, thanks :)

**Comment by frankko** [comment]
Looks like something in a recent Sketch update broke "Updated All Bitmaps" (so I don't think it has anything to do with you using Google Drive). I will try to figure it out. Thanks for the report.

**Comment by o-l-e** [comment]
Thank you so much, i really appreciate it. This plugin is so useful, have you considered adding more features to it by any chance? :)

**Comment by RickNunn** [comment]
Hey @frankko - I just wanted to drop a comment here to say that I too would love to see this plugin updated to work with the latest version of Sketch. I've actually downgraded again so I can continue using it. 

I would also love to be able to donate/buy you a coffee & a sandwich for your efforts on this plugin. It's such awesome functionality that I can't believe sketch don't have by default. Let me know if there is a way I can do this.

**Comment by o-l-e** [comment]
+1 i would also donate to get this working again.

**Comment by Qiuyang33** [comment]
me too
