### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [frankko/Place-Linked-Bitmap#2]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by frankko** [comment]
Thanks, Ale. Just replacing `setPatternImage:` with `setImage:` crashes Sketch. Is there more to it that I’m missing? Does `setImage:` take an NSImage like `setPatternImage:` did?

This will crash Sketch 39 (a shape layer is selected and “filePath” is a local file URL):

```
var newImage = [[NSImage alloc] initWithContentsOfFile:filePath];
var fill = layer.style().fills().firstObject();
[fill setImage:newImage];
[fill setFillType:4];
[fill setPatternFillType:1];
```

replacing `setImage:` with `setPatternImage:` will not crash Sketch and works as expected.

**Comment by frankko** [comment]
If anybody happens upon this, `setImage` takes an MSImage, not an NSImage.
