### ISSUE TITLE
doesn't work with 46.2

### ISSUE THREAD

**Issue by stdk00** [frankko/Place-Linked-Bitmap#7]
I try to "update all bitmaps" but nothing happens. can you please help me?
Thank you

**Comment by swizenfeld** [comment]
Any updates on this? Would love to start using this but there are issues with the latest sketch version. 

Great idea and job on this!

**Comment by frankko** [comment]
I don’t think 46.2 introduced any conflicts with the plugin. 

One thing to keep in mind: the plugin is context sensitive. So if you have a bitmap in artboard 1, but have artboard 2 selected, the plugin won’t update the bitmaps in artboard 1. If you want to update the entire document, either make sure no artboards are selected or all artboards are selected.

If that’s not the problem, the only advice I can give is to open the Console app in /Applications/Utilities. Assuming you’re on either macOS Sierra or High Sierra, in the left sidebar, under Reports, find ~/Library/Logs and hit the triangle to expand it. Find com.bohemiancoding.sketch3 in the list and select it. Go back to Sketch, try to run the update command, then go back to the Console and see what it says. If you see something about the original file not being found, double-check that it’s at the location that the plugin thinks it’s supposed to be at.

**Comment by stdk00** [comment]
just to give you some feedback, I've reinstalled sketch and all plugins and restarted my mac. everything is working again, so I don't know what really happened. if this problem comes up again I'll let you know.

Thanks for the great plugin and I hope to see more improvements in the future because there's plenty of room to make this even more helpful and meaningful, because there's nothing similar out there as far as I can tell.
